### ISSUE TITLE
enhancement: 16bit ram chip support

### ISSUE THREAD

**Issue by pluspeople** [Mathesar/14mhz-accelerator#12]
Love the design (despite the DMA issue), would it be possible to enhance the design to utilize 16bit sram chips instead of 2x 8bit chips ?
This would give the following advantages:
- It would be possible to fit 2x 4mbit 16bit chips (1.75 addressable) without having to increase pcb size (ok tsop-44 is 5mm longer than tsop-32)
- One could choose to install either 1 or 2 chips (more options / choice)
- If only 1mb is wanted as then only one ram chip needs to be fittet (enhanced simplicity)
- As of writing a 4mbit 16bit chip costs 7.07euro vs 8.50euro for 2x 4mbit 8bit chips (slightly cheaper)

As an example I have been looking at the AS6C8016-55ZIN chip which is 5v compatible, and 55ns speed (I believe it only need to be 70ns or better to work fullspeed at 14mhz?)

**Comment by Mathesar** [comment]
As commented in another issue, it could be done. However, quite some stuff would need to be changed. The address decoder has to be changed of course, as well the RAM CS and OE / WR strobes as these are currently layed out for a high byte and low byte RAM chip. Also, the RAM would have to be added via a command in the startup sequence as it will not be auto recognized.
