### ISSUE TITLE
Newly built, no 1mb ranger memory reported

### ISSUE THREAD

**Issue by opengiveback** [Mathesar/14mhz-accelerator#13]
Hi, thanks for the design.

I built one configured with all the circuits, and it worked right away. However, no ranger RAM is being reported, and measuring voltage on J2 always gets me 2.57V.

Then I found, my jumper JP2 wasn't soldered properly (all three shorted), and some solder was shorting pins of U4. However, after fixing it, still does not have any of the accelerated RAM, 1.10 max speed improvement to Amiga 600 in SysInfo, and reports 12MHz consistently.

I'd have to ask, the possibility of RAM itself not working is not what is causing the ranger RAM not to be there, right? It's some logic IC that actually reports the ranger RAM on init that's at fault? And if the RAM was faulty, it would simply freeze?
Or should I try with other RAM chips?
Or perhaps, something else entirely needs to be done to make it work? All the jumpers are shorted at pin 1 (left).

Thanks in advance

P.S. I intend to build and sell at least 10 of them, and give back 15% of the profit to the author, as per my OpenGiveBack.org idea :)

**Comment by Mathesar** [comment]
The Amiga scans the ranger memory during boot time. So as it is not detected it does not use it. The computer won't freeze.
I would suspect the logic IC's that decode the memory addresses for the memory so U8/U9/U10. Check all solder joints, shorts, etc. It could also be the NE555 circuit that disables RAM. What is the level on pin 3 of U11? It should be low. You could also try setting JP4 to 2-3 for testing to disable the NE555 circuit.

**Comment by opengiveback** [comment]
Triple checked all/touched up on all the relevant solder joints, pin 3 of U11 showed 0.05V (or was it 0.5V), so low, and also disabled NE555 by setting JP4 to 2-3. And the ram still was not there upon booting.

Then I changed the memory chips, for the other ones I ordered (was ALLIANCE AS6C4008-55SIN chips, then tried with HM628512CLFP-7). With the JP4 set to 2-3. And still the same result as at the start, Accelerator works, but none of the ranger RAM detected.

So, I guess the only conclusion is, some logic circuit is not working (U8, U9, U10), and needs to be replaced?

Could I test at least the NE555 by having 512KB slow RAM in expansion slot, and trying to see that slow RAM reported when holding reset keys for 6, 7 seconds, and JP4 is set to 1-2? (Because I couldn't see it before, whether held the combination for 7 seconds or not)... It should have the expansion port slow 512KB ram working now when the JP4 is set to 2-3, correct? And yet, it again boots into workbench and shows only the 512KB chip RAM, in AmiTestKit and SysInfo also. I cant understand why that would be? A pin in the CPU socket perhaps, but they all were crisp as was the ones on the new MC68HC000....

I shall try soldering another example on a different PCB, to rule out PCB manufacturing faults or a single logic chip of the ordered batch being faulty. But if you have any further advice on what could be the problem with this one, I would appreciate it highly.

**Comment by opengiveback** [comment]
After checking on the type of memory chips, the one you listed in the BOM is a TSOP II, and both of these are TSOP I (sTSOP or other one just refered as SOP), the pinout is very different (for the ISSI chips you used and defined in BOM, but for some it is the same in both). So it seemed it might have been wrong type of memory chips that was the issue. First chose wrong extension of the model, then ordered alternative for wrong chip. Surely the wrong pinout would also cause the problem with unadressable expansion port slow RAM.
But, it seems one of the types of memory chips I used (the second, HITACHI ones) has the desired pinout.

![hitachi](https://github.com/Mathesar/14mhz-accelerator/assets/148102907/291734d5-4cb7-4481-8c8c-5f7813e99087)
I see other manufacturers have same pinout in sTSOP and TSOP II... actually the HITACHI HM628512CLFP-7 I used, has **almost same pinout as the ISSI IS61C5128AS-25TLI from the BOM, except address lines A18 and A17 are in each other's places**, which being 8 bit memory I didn't think it should matter. So I shall make another example with the HITACHI chips, and see how that goes...

![image](https://github.com/Mathesar/14mhz-accelerator/assets/148102907/f7bdc836-1773-4a3f-b72e-84a1b6ac6ceb)

The other RAM chip type I received are not the exact same ones I ordered, but a "compatible" part, only it isn't compatible, as it has a different pinout between it's sTSOP and TSOP II variant... so there's an example how suppliers getting creative can create problems, yet, the HITACHI HM628512CLFP-7 SOP chips **should** work, correct? The pins were carefully bent into shape to reduce the footprint width for the millimeter SOP differs from TSOP II.
![accelerator](https://github.com/Mathesar/14mhz-accelerator/assets/148102907/b39e9fab-3013-4a3d-aa37-bffb9e8bd6c1)

**Comment by opengiveback** [comment]
Update, resoldered RAM chips, stopped turning on, unsoldered them again, started working without RAM again. Soldered another example PCB, with new chips, presoldered pads, more careful to be sure all pins connected good, the other example refuses to turn on also, black screen, waiting for some CY62148ELL-45ZSXI Cypress chips (from your forum link to list of compatible chips, checked datasheet to confirm pinout as in BOM part) to arrive, with exact dimensions.

**Comment by opengiveback** [comment]
Hi, so the Cypress RAM arrived, soldered it on, now all works great! :)

Thanks for the replies, and please disclose paypal email or similar means for me to donate the 15% of earnings from sold examples of this great design, as per OpenGiveBack.org.

**Comment by Mathesar** [comment]
> Hi, so the Cypress RAM arrived, soldered it on, now all works great! :)
> 
> Thanks for the replies, and please disclose paypal email or similar means for me to donate the 15% of earnings from sold examples of this great design, as per OpenGiveBack.org.

Hi Opengiveback,

You had quite a journey with your build. I'm sorry I couldn't check your RAM pinouts before you tried. But luckily it all works now! 
And no donations please, this design is free!
