### ISSUE TITLE
Other address range for A600/2MB Chip-RAM compatibility?

### ISSUE THREAD

**Issue by Lalarian** [Mathesar/14mhz-accelerator#3]
Hello!

I wondered, if it would be possible to add a jumper for changing the address range?
While was searching for affordable solutions, for making the A600 a capable WHDLoad machine (which would require FastRAM and an 68010 for the quit-key-feature), I was also including A500 expansions into the search, since 
there are cheap adapters that disable the A600's onboard 68k (like Lemaru's PLCC2DIP), which allow plugging 68K DIPs into the A600.

So I found a video about your new accelerator on YouTube and then the thread on abime. 
There I read you used the ChipRAM range for not having to bother with autoconfig.
Putting an 68010 in the socket of this board shouldn't be a problem, as it's fully compatible.

So the only problem would probably be the conflict with an A600 that has 2MB ChipRAM overall from the trapdoor slot.
I think autoconfig isn't too important (is it?), as we could automatically add the RAM of the board from startup-sequence/user-startup, using Amiga's 'addmem' tool, which would basically always be possible, when booting the user's own system from HD/CF/SD before starting WHDLoad.

So, would it be possible to place the board's RAM as 8MB-FastRAM from 0x200000 to 0x9FFFFF? Maybe just by swapping some address lines around using a jumper (as this project is of course intended to stay affordable)?
Thank you! :)

**Comment by Mathesar** [comment]
Hello Lalarian,

The 1MB ram on this board is assigned to $C00000. The optional 1MB chipram in the A600's trapdoor slot is assigned to $100000. So there should be no conflict! 
BTW, for an A600 this design could be simplified by removing the E clock synchronisation logic ;-)

**Comment by Lalarian** [comment]
Thank you! That's great news!
I thought that the 600's ChipRAM extension was at $C00000. But I now had a look at the memory map and it's called "PseudoFast-RAM", hm, OK.
So I am gonna try to upgrade my 600, soon! I will report when I'm done, just for confirmation!
:)
