### ISSUE TITLE
Platform agnostic?

### ISSUE THREAD

**Issue by dlxmax** [Mathesar/14mhz-accelerator#4]
Is there anything that would keep the accelerator-only version from working on another 68k platform, such as a Mac or Atari?

**Comment by Mathesar** [comment]
Probably only the RAM. I don't know the memory layout of the ST or the Macintosh but I can imagine that the $C00000..$CFFFFF range is already taken. Other than that I see no fundamental reason why it wouldn't work. Best way to find out is to try it out with an accelerator-only version.

**Comment by dlxmax** [comment]
I measured for putting one of these in a Mac Plus, but the board is at least 3mm too long to fit, interfering with the power connector. Trying to beat it with height would result in case interference. I suppose the PCB could be shaved at the bottom, as it appears those lines are for the memory chips...but that's such a dirty hack lol. I really hoped to give it a go!
