### ISSUE TITLE
Disable switch?

### ISSUE THREAD

**Issue by MarkieV** [Mathesar/14mhz-accelerator#5]
Hi there

In the readme it says 'and disable switch for the Amiga' I looked several times at the schematics,
but I can not find a switch.
Do I have to make something with two 74F157 switches (like in the old version) to switch between
7MHz and 14MHz? or do I overlook something.

I would like to make a small PCB that sits under the 68000 with only the clock doubler as I already
have 8MB fastram.

Grtzz  Mark

**Comment by Mathesar** [comment]
On page 3 of the schematic you can find a 555 timer based circuit. This is the disable switch that works by holding the ctrl-amiga-amiga key combo down for more that 6 seconds or so.
However, it does not disable the clock-doubler but only the ranger (fast) ram. In practice this has virtually the same effect as without fast ram the speed of the 68000 is governed by the clock speed of the Amiga memory bus. If you wish you can replace the 555 by a manual switch. This switch would have to control the RAM_DIS signal: high=disabled, low=enabled.

**Comment by Mathesar** [comment]
One more thing. Combining this accelerator with fast ram sitting on the Amiga bus will not be very fast as that ram does not run at the full 14MHz. My guestimate is that it will make your Amiga about 1.5 times faster than stock. 
(based on this text: [http://www.cucug.org/amiga/amiinfo/reviews/Accelerator14M.txt](url)
