### ISSUE TITLE
Can this be set to 16 or 20 mhz ?

### ISSUE THREAD

**Issue by Glmaxter** [Mathesar/14mhz-accelerator#6]
I heard some of these cpu chips are set to 14,16 and 20 mhz. Can this be set somehow ?

**Comment by Mathesar** [comment]
The accelerator always runs the installed CPU at 14MHz. You cannot set any other speeds.
The CPU has to be fast enough to handle that so 16MHz, 20MHz or faster rated CPU's will be fine.
