### ISSUE TITLE
Sysinfo shows CPU@11.30 Mhz and not 14 Mhz.

### ISSUE THREAD

**Issue by felmur** [Mathesar/14mhz-accelerator#7]
Hi Mathesar and thanks for this beautiful project.

I had the PCB made by PCBWay, then I ordered the components for the accelerator only (CPU and the 4 ICs and those few smd passive components).
After having soldered everything, I tried to mount it in my A500 rev6, already equipped with this ram expansion, 2MB version (0.5 chip, 1.5 fast):
https://amigastore.eu/en/710-amiga-500-512kb2mb-memory-expansion-rtc.html#/
When I run SysInfo it calculates a clock speed of 11.30 Mhz (and not 14 Mhz) and a very small increase in performance (1.04 vs A600).
What do you think?
Regards.

**Comment by Mathesar** [comment]
Hi Felmur,

The 2MB trapdoor expansion from amigastore.eu gives you 1.5MB "pseudo" fast RAM. Not real fast RAM. As a result the 14MHz CPU can not run at full speed. This accelerator only reaches its full speed when the 1MB of local fast RAM is also populated. Without it, you will only see this small speed increase that you see now.

**Comment by felmur** [comment]
Hi Mathesar,
In fact, by removing the expansion, the speed measured by SysInfo goes up to 11.70 Mhz and the performance goes up to 1.05 vs A600. Nothing changes if I use the PC CDAC instead of the accelerator internal clock.
If so, it's not worth using this booster without installing ram memory as well.
Well, patience. Thanks for the reply.

**Comment by Mathesar** [comment]
I wouldn't really worry about 11.70 MHz vs 11.30 MHz, that is just noise.
The RAM expansion won't make your system slower. You can install the RAM memory on the accelerator board and still use the 2MB expansion. However, the first 1Mb of slow ram won't be used anymore as it will be overruled by the accelerator RAM.
So, you keep the same amount of memory (2.5Mb total) but the first 1Mb of slow RAM will turn into real fast RAM.

**Comment by felmur** [comment]
Thanks Mathesar, I had already started looking for the rest of the components to complete the accelerator + ram.

**Comment by felmur** [comment]
Due to an error in the order of the remaining components from Chinese companies, I had to wait until today to be able to finish the accelerator, which I just did. And... It Works! Sysinfo tells me that my A500 is now 2.70 times faster than an A600 and 1.22 times faster than an Amiga1200. Thanks for this wonderful project!

**Comment by Mathesar** [comment]
Good to hear!
Enjoy!
